import 'package:islami_c20/features/home/taps/quran_screen/model/sura_model.dart';

class SurasData {
  static List<SuraModel> suras = [
    SuraModel(
    number: 1,
    verses: 7,
    arabicName: 'الفاتحة',
    englishName: 'Al-Fatihah',
  ),
    SuraModel(
      number: 2,
      verses: 286,
      arabicName: 'البقرة',
      englishName: 'Al-Baqarah',
    ),
    SuraModel(
      number: 3,
      verses: 200,
      arabicName: 'آل عمران',
      englishName: 'Ali \'Imran',
    ),
    SuraModel(
      number: 4,
      verses: 176,
      arabicName: 'النساء',
      englishName: 'An-Nisa',
    ),
    SuraModel(
      number: 5,
      verses: 120,
      arabicName: 'المائدة',
      englishName: 'Al-Ma\'idah',
    ),
    SuraModel(
      number: 6,
      verses: 165,
      arabicName: 'الأنعام',
      englishName: 'Al-An\'am',
    ),
    SuraModel(
      number: 7,
      verses: 206,
      arabicName: 'الأعراف',
      englishName: 'Al-A\'raf',
    ),
    SuraModel(
      number: 8,
      verses: 75,
      arabicName: 'الأنفال',
      englishName: 'Al-Anfal',
    ),
    SuraModel(
      number: 9,
      verses: 129,
      arabicName: 'التوبة',
      englishName: 'At-Tawbah',
    ),
    SuraModel(
      number: 10,
      verses: 109,
      arabicName: 'يونس',
      englishName: 'Yunus',
    ),
    SuraModel(
      number: 11,
      verses: 123,
      arabicName: 'هود',
      englishName: 'Hud',
    ),
    SuraModel(
      number: 12,
      verses: 111,
      arabicName: 'يوسف',
      englishName: 'Yusuf',
    ),
    SuraModel(
      number: 13,
      verses: 43,
      arabicName: 'الرعد',
      englishName: 'Ar-Ra\'d',
    ),
    SuraModel(
      number: 14,
      verses: 52,
      arabicName: 'إبراهيم',
      englishName: 'Ibrahim',
    ),
    SuraModel(
      number: 15,
      verses: 99,
      arabicName: 'الحجر',
      englishName: 'Al-Hijr',
    ),
    SuraModel(
      number: 16,
      verses: 128,
      arabicName: 'النحل',
      englishName: 'An-Nahl',
    ),
    SuraModel(
      number: 17,
      verses: 111,
      arabicName: 'الإسراء',
      englishName: 'Al-Isra',
    ),
    SuraModel(
      number: 18,
      verses: 110,
      arabicName: 'الكهف',
      englishName: 'Al-Kahf',
    ),
    SuraModel(
      number: 19,
      verses: 98,
      arabicName: 'مريم',
      englishName: 'Maryam',
    ),
    SuraModel(
      number: 20,
      verses: 135,
      arabicName: 'طه',
      englishName: 'Ta-Ha',
    ),
    SuraModel(
      number: 21,
      verses: 112,
      arabicName: 'الأنبياء',
      englishName: 'Al-Anbiya',
    ),
    SuraModel(
      number: 22,
      verses: 78,
      arabicName: 'الحج',
      englishName: 'Al-Hajj',
    ),
    SuraModel(
      number: 23,
      verses: 118,
      arabicName: 'المؤمنون',
      englishName: 'Al-Mu\'minun',
    ),
    SuraModel(
      number: 24,
      verses: 64,
      arabicName: 'النور',
      englishName: 'An-Nur',
    ),
    SuraModel(
      number: 25,
      verses: 77,
      arabicName: 'الفرقان',
      englishName: 'Al-Furqan',
    ),
    SuraModel(
      number: 26,
      verses: 227,
      arabicName: 'الشعراء',
      englishName: 'Ash-Shu\'ara',
    ),
    SuraModel(
      number: 27,
      verses: 93,
      arabicName: 'النمل',
      englishName: 'An-Naml',
    ),
    SuraModel(
      number: 28,
      verses: 88,
      arabicName: 'القصص',
      englishName: 'Al-Qasas',
    ),
    SuraModel(
      number: 29,
      verses: 69,
      arabicName: 'العنكبوت',
      englishName: 'Al-Ankabut',
    ),
    SuraModel(
      number: 30,
      verses: 60,
      arabicName: 'الروم',
      englishName: 'Ar-Rum',
    ),
    SuraModel(
      number: 31,
      verses: 34,
      arabicName: 'لقمان',
      englishName: 'Luqman',
    ),
    SuraModel(
      number: 32,
      verses: 30,
      arabicName: 'السجدة',
      englishName: 'As-Sajdah',
    ),
    SuraModel(
      number: 33,
      verses: 73,
      arabicName: 'الأحزاب',
      englishName: 'Al-Ahzab',
    ),
    SuraModel(
      number: 34,
      verses: 54,
      arabicName: 'سبأ',
      englishName: 'Saba',
    ),
    SuraModel(
      number: 35,
      verses: 45,
      arabicName: 'فاطر',
      englishName: 'Fatir',
    ),
    SuraModel(
      number: 36,
      verses: 83,
      arabicName: 'يس',
      englishName: 'Ya-Sin',
    ),
    SuraModel(
      number: 37,
      verses: 182,
      arabicName: 'الصافات',
      englishName: 'As-Saffat',
    ),
    SuraModel(
      number: 38,
      verses: 88,
      arabicName: 'ص',
      englishName: 'Sad',
    ),
    SuraModel(
      number: 39,
      verses: 75,
      arabicName: 'الزمر',
      englishName: 'Az-Zumar',
    ),
    SuraModel(
      number: 40,
      verses: 85,
      arabicName: 'غافر',
      englishName: 'Ghafir',
    ),
    SuraModel(
      number: 41,
      verses: 54,
      arabicName: 'فصلت',
      englishName: 'Fussilat',
    ),
    SuraModel(
      number: 42,
      verses: 53,
      arabicName: 'الشورى',
      englishName: 'Ash-Shura',
    ),
    SuraModel(
      number: 43,
      verses: 89,
      arabicName: 'الزخرف',
      englishName: 'Az-Zukhruf',
    ),
    SuraModel(
      number: 44,
      verses: 59,
      arabicName: 'الدخان',
      englishName: 'Ad-Dukhan',
    ),
    SuraModel(
      number: 45,
      verses: 37,
      arabicName: 'الجاثية',
      englishName: 'Al-Jathiyah',
    ),
    SuraModel(
      number: 46,
      verses: 35,
      arabicName: 'الأحقاف',
      englishName: 'Al-Ahqaf',
    ),
    SuraModel(
      number: 47,
      verses: 38,
      arabicName: 'محمد',
      englishName: 'Muhammad',
    ),
    SuraModel(
      number: 48,
      verses: 29,
      arabicName: 'الفتح',
      englishName: 'Al-Fath',
    ),
    SuraModel(
      number: 49,
      verses: 18,
      arabicName: 'الحجرات',
      englishName: 'Al-Hujurat',
    ),
    SuraModel(
      number: 50,
      verses: 45,
      arabicName: 'ق',
      englishName: 'Qaf',
    ),
    SuraModel(
      number: 51,
      verses: 60,
      arabicName: 'الذاريات',
      englishName: 'Adh-Dhariyat',
    ),
    SuraModel(
      number: 52,
      verses: 49,
      arabicName: 'الطور',
      englishName: 'At-Tur',
    ),
    SuraModel(
      number: 53,
      verses: 62,
      arabicName: 'النجم',
      englishName: 'An-Najm',
    ),
    SuraModel(
      number: 54,
      verses: 55,
      arabicName: 'القمر',
      englishName: 'Al-Qamar',
    ),
    SuraModel(
      number: 55,
      verses: 78,
      arabicName: 'الرحمن',
      englishName: 'Ar-Rahman',
    ),
    SuraModel(
      number: 56,
      verses: 96,
      arabicName: 'الواقعة',
      englishName: 'Al-Waqi\'ah',
    ),
    SuraModel(
      number: 57,
      verses: 29,
      arabicName: 'الحديد',
      englishName: 'Al-Hadid',
    ),
    SuraModel(
      number: 58,
      verses: 22,
      arabicName: 'المجادلة',
      englishName: 'Al-Mujadila',
    ),
    SuraModel(
      number: 59,
      verses: 24,
      arabicName: 'الحشر',
      englishName: 'Al-Hashr',
    ),
    SuraModel(
      number: 60,
      verses: 13,
      arabicName: 'الممتحنة',
      englishName: 'Al-Mumtahanah',
    ),
    SuraModel(
      number: 61,
      verses: 14,
      arabicName: 'الصف',
      englishName: 'As-Saff',
    ),
    SuraModel(
      number: 62,
      verses: 11,
      arabicName: 'الجمعة',
      englishName: 'Al-Jumu\'ah',
    ),
    SuraModel(
      number: 63,
      verses: 11,
      arabicName: 'المنافقون',
      englishName: 'Al-Munafiqun',
    ),
    SuraModel(
      number: 64,
      verses: 18,
      arabicName: 'التغابن',
      englishName: 'At-Taghabun',
    ),
    SuraModel(
      number: 65,
      verses: 12,
      arabicName: 'الطلاق',
      englishName: 'At-Talaq',
    ),
    SuraModel(
      number: 66,
      verses: 12,
      arabicName: 'التحريم',
      englishName: 'At-Tahrim',
    ),
    SuraModel(
      number: 67,
      verses: 30,
      arabicName: 'الملك',
      englishName: 'Al-Mulk',
    ),
    SuraModel(
      number: 68,
      verses: 52,
      arabicName: 'القلم',
      englishName: 'Al-Qalam',
    ),
    SuraModel(
      number: 69,
      verses: 52,
      arabicName: 'الحاقة',
      englishName: 'Al-Haqqah',
    ),
    SuraModel(
      number: 70,
      verses: 44,
      arabicName: 'المعارج',
      englishName: 'Al-Ma\'arij',
    ),
    SuraModel(
      number: 71,
      verses: 28,
      arabicName: 'نوح',
      englishName: 'Nuh',
    ),
    SuraModel(
      number: 72,
      verses: 28,
      arabicName: 'الجن',
      englishName: 'Al-Jinn',
    ),
    SuraModel(
      number: 73,
      verses: 20,
      arabicName: 'المزمل',
      englishName: 'Al-Muzzammil',
    ),
    SuraModel(
      number: 74,
      verses: 56,
      arabicName: 'المدثر',
      englishName: 'Al-Muddaththir',
    ),
    SuraModel(
      number: 75,
      verses: 40,
      arabicName: 'القيامة',
      englishName: 'Al-Qiyamah',
    ),
    SuraModel(
      number: 76,
      verses: 31,
      arabicName: 'الإنسان',
      englishName: 'Al-Insan',
    ),
    SuraModel(
      number: 77,
      verses: 50,
      arabicName: 'المرسلات',
      englishName: 'Al-Mursalat',
    ),
    SuraModel(
      number: 78,
      verses: 40,
      arabicName: 'النبأ',
      englishName: 'An-Naba',
    ),
    SuraModel(
      number: 79,
      verses: 46,
      arabicName: 'النازعات',
      englishName: 'An-Nazi\'at',
    ),
    SuraModel(
      number: 80,
      verses: 42,
      arabicName: 'عبس',
      englishName: 'Abasa',
    ),
    SuraModel(
      number: 81,
      verses: 29,
      arabicName: 'التكوير',
      englishName: 'At-Takwir',
    ),
    SuraModel(
      number: 82,
      verses: 19,
      arabicName: 'الانفطار',
      englishName: 'Al-Infitar',
    ),
    SuraModel(
      number: 83,
      verses: 36,
      arabicName: 'المطففين',
      englishName: 'Al-Mutaffifin',
    ),
    SuraModel(
      number: 84,
      verses: 25,
      arabicName: 'الانشقاق',
      englishName: 'Al-Inshiqaq',
    ),
    SuraModel(
      number: 85,
      verses: 22,
      arabicName: 'البروج',
      englishName: 'Al-Buruj',
    ),
    SuraModel(
      number: 86,
      verses: 17,
      arabicName: 'الطارق',
      englishName: 'At-Tariq',
    ),
    SuraModel(
      number: 87,
      verses: 19,
      arabicName: 'الأعلى',
      englishName: 'Al-A\'la',
    ),
    SuraModel(
      number: 88,
      verses: 26,
      arabicName: 'الغاشية',
      englishName: 'Al-Ghashiyah',
    ),
    SuraModel(
      number: 89,
      verses: 30,
      arabicName: 'الفجر',
      englishName: 'Al-Fajr',
    ),
    SuraModel(
      number: 90,
      verses: 20,
      arabicName: 'البلد',
      englishName: 'Al-Balad',
    ),
    SuraModel(
      number: 91,
      verses: 15,
      arabicName: 'الشمس',
      englishName: 'Ash-Shams',
    ),
    SuraModel(
      number: 92,
      verses: 21,
      arabicName: 'الليل',
      englishName: 'Al-Layl',
    ),
    SuraModel(
      number: 93,
      verses: 11,
      arabicName: 'الضحى',
      englishName: 'Ad-Duha',
    ),
    SuraModel(
      number: 94,
      verses: 8,
      arabicName: 'الشرح',
      englishName: 'Ash-Sharh',
    ),
    SuraModel(
      number: 95,
      verses: 8,
      arabicName: 'التين',
      englishName: 'At-Tin',
    ),
    SuraModel(
      number: 96,
      verses: 19,
      arabicName: 'العلق',
      englishName: 'Al-\'Alaq',
    ),
    SuraModel(
      number: 97,
      verses: 5,
      arabicName: 'القدر',
      englishName: 'Al-Qadr',
    ),
    SuraModel(
      number: 98,
      verses: 8,
      arabicName: 'البينة',
      englishName: 'Al-Bayyinah',
    ),
    SuraModel(
      number: 99,
      verses: 8,
      arabicName: 'الزلزلة',
      englishName: 'Az-Zalzalah',
    ),
    SuraModel(
      number: 100,
      verses: 11,
      arabicName: 'العاديات',
      englishName: 'Al-\'Adiyat',
    ),
    SuraModel(
      number: 101,
      verses: 11,
      arabicName: 'القارعة',
      englishName: 'Al-Qari\'ah',
    ),
    SuraModel(
      number: 102,
      verses: 8,
      arabicName: 'التكاثر',
      englishName: 'At-Takathur',
    ),
    SuraModel(
      number: 103,
      verses: 3,
      arabicName: 'العصر',
      englishName: 'Al-\'Asr',
    ),
    SuraModel(
      number: 104,
      verses: 9,
      arabicName: 'الهمزة',
      englishName: 'Al-Humazah',
    ),
    SuraModel(
      number: 105,
      verses: 5,
      arabicName: 'الفيل',
      englishName: 'Al-Fil',
    ),
    SuraModel(
      number: 106,
      verses: 4,
      arabicName: 'قريش',
      englishName: 'Quraysh',
    ),
    SuraModel(
      number: 107,
      verses: 7,
      arabicName: 'الماعون',
      englishName: 'Al-Ma\'un',
    ),
    SuraModel(
      number: 108,
      verses: 3,
      arabicName: 'الكوثر',
      englishName: 'Al-Kawthar',
    ),
    SuraModel(
      number: 109,
      verses: 6,
      arabicName: 'الكافرون',
      englishName: 'Al-Kafirun',
    ),
    SuraModel(
      number: 110,
      verses: 3,
      arabicName: 'النصر',
      englishName: 'An-Nasr',
    ),
    SuraModel(
      number: 111,
      verses: 5,
      arabicName: 'المسد',
      englishName: 'Al-Masad',
    ),
    SuraModel(
      number: 112,
      verses: 4,
      arabicName: 'الإخلاص',
      englishName: 'Al-Ikhlas',
    ),
    SuraModel(
      number: 113,
      verses: 5,
      arabicName: 'الفلق',
      englishName: 'Al-Falaq',
    ),
    SuraModel(
      number: 114,
      verses: 6,
      arabicName: 'الناس',
      englishName: 'An-Nas',
    ),];

  static List<SuraModel> recentSuras =[];
}